# Generated by Django 3.0.2 on 2020-01-25 18:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jseeker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
