# Generated by Django 3.0.2 on 2020-03-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0002_jseekerprofile_jseekerskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jseekerskill',
            old_name='skills',
            new_name='skill',
        ),
    ]
