# Generated by Django 3.0.2 on 2020-03-03 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseekerapp', '0003_auto_20200302_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='JseekerEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jseekerprofile',
            name='education',
            field=models.ManyToManyField(to='jobseekerapp.JseekerEdu'),
        ),
    ]
