# Generated by Django 3.0.2 on 2020-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0004_auto_20200303_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jseekeredu',
            old_name='edu',
            new_name='course',
        ),
        migrations.AddField(
            model_name='jseekeredu',
            name='datefrom',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jseekeredu',
            name='dateto',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jseekeredu',
            name='eduinst',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
