# Generated by Django 3.0.2 on 2020-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0005_auto_20200303_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jseekeredu',
            name='eduinst',
            field=models.CharField(max_length=50),
        ),
    ]
