# Generated by Django 3.0.2 on 2020-03-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0006_auto_20200303_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jseekeredu',
            name='datefrom',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='jseekeredu',
            name='dateto',
            field=models.DateField(blank=True),
        ),
    ]
