# Generated by Django 3.0.2 on 2020-03-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0007_auto_20200303_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jseekeredu',
            old_name='course',
            new_name='course_completed',
        ),
        migrations.RenameField(
            model_name='jseekeredu',
            old_name='datefrom',
            new_name='date_ended',
        ),
        migrations.RenameField(
            model_name='jseekeredu',
            old_name='dateto',
            new_name='date_started',
        ),
        migrations.RenameField(
            model_name='jseekeredu',
            old_name='eduinst',
            new_name='institute',
        ),
    ]
