# Generated by Django 3.0.2 on 2020-03-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0008_auto_20200303_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jseekeredu',
            old_name='course_completed',
            new_name='degree',
        ),
        migrations.AddField(
            model_name='jseekeredu',
            name='field_of_study',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
