# Generated by Django 3.0.2 on 2020-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0009_auto_20200303_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jseekeredu',
            name='field_of_study',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
