# Generated by Django 3.0.2 on 2020-03-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0013_auto_20200303_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jseekeredu',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jseekeredu',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
