# Generated by Django 3.0.2 on 2020-03-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterapp', '0003_remove_vacancy_applied_user'),
        ('jobseekerapp', '0015_remove_vacancyapply_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapply',
            name='vacancy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruiterapp.Vacancy'),
            preserve_default=False,
        ),
    ]
