# Generated by Django 3.0.2 on 2020-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterapp', '0003_remove_vacancy_applied_user'),
        ('jobseekerapp', '0017_remove_vacancyapply_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapply',
            name='vacancy',
            field=models.ManyToManyField(to='recruiterapp.Vacancy'),
        ),
    ]
