# Generated by Django 3.0.2 on 2020-03-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterapp', '0003_remove_vacancy_applied_user'),
        ('jobseekerapp', '0018_vacancyapply_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapply',
            name='vacancy',
            field=models.ManyToManyField(null=True, to='recruiterapp.Vacancy'),
        ),
    ]
