# Generated by Django 3.0.2 on 2020-03-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0020_auto_20200304_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VacancyApply',
        ),
    ]
