# Generated by Django 3.0.2 on 2020-04-22 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('jobcategory', models.IntegerField(choices=[(1, 'IT/ Telecomunication'), (2, 'Construction/ Engineering/ Architects'), (3, 'Health Care/ Pharma/ Biotech/ Medical/ R&D'), (4, 'Banking/ Insurance/ Financial Services'), (5, 'Teaching/ Education'), (6, 'General Management/ Administration')])),
                ('title', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('deadline', models.DateField()),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
