# Generated by Django 3.0.2 on 2020-03-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0015_remove_vacancyapply_vacancy'),
        ('recruiterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='applied_user',
            field=models.ManyToManyField(to='jobseekerapp.VacancyApply'),
        ),
    ]
