# Generated by Django 3.0.2 on 2020-02-01 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruiterprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('currentcompany', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='File/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
