# Generated by Django 3.0.2 on 2020-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterapp', '0002_recruiterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='File/'),
        ),
    ]
