# Generated by Django 3.0.2 on 2020-03-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterapp', '0002_vacancy_applied_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='applied_user',
        ),
    ]
