# Generated by Django 3.0.2 on 2020-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterapp', '0004_recruiterprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='profession',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
