# Generated by Django 3.0.2 on 2020-04-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.IntegerField(choices=[(1, 'IT/ Telecomunication'), (2, 'Construction/ Engineering/ Architects'), (3, 'Health Care/ Pharma/ Biotech/ Medical/ R&D'), (4, 'Banking/ Insurance/ Financial Services'), (5, 'Teaching/ Education'), (6, 'General Management/ Administration')]),
        ),
    ]
