# Generated by Django 3.0.2 on 2020-03-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='connections',
        ),
    ]
