# Generated by Django 3.0.2 on 2020-01-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0002_auto_20200115_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('R', 'Recruiter'), ('J', 'Jobseeker')], default='R', max_length=1),
        ),
    ]
