# Generated by Django 3.0.2 on 2020-01-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0003_auto_20200115_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Mob_Number',
            new_name='Mobile_Number',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
