# Generated by Django 3.0.2 on 2020-02-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0005_auto_20200125_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='currentcompany',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, upload_to='File/'),
        ),
    ]
